apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: uurapport-frontend
  namespace: team-researchops
  labels:
    team: team-researchops

spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  ingresses:
    - 'https://uurapport.ansatt.nav.no'
    - 'https://a11y-statement-ny.ansatt.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: uurapport-backend
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        groups:
          - id: '07bca51b-e5dc-484a-ac09-685e61244b6b' #admins
    sidecar:
      enabled: true
      autoLogin: true
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: '20m'
      memory: 128Mi
  env:
    - name: NAIS_CLUSTER_NAME
      value: "prod-gcp"
    - name: BACKEND_APP_NAME
      value: "uurapport-backend"
    - name: VITE_WONDERWALL_INGRESS
      value: "$(WONDERWALL_INGRESS)"